### ISSUE TITLE
Mycoria says it uses "Modern cryptography"

### ISSUE THREAD

**Issue by bmullan** [mycoria/mycoria#2]
When you get time can you add a paragraph about what the Cryptography consists of?

thanks

**Comment by dhaavi** [comment]
There is a section about this here: https://mycoria.org/concept/#cryptography

Is this what you expect, or would you like more details? If so, what information are you looking for?

**Comment by bmullan** [comment]
@dhaavi 
Thanks... yes thats exactly what I was asking about.
