### ISSUE TITLE
mycoria config generate give error (I think it should be geoip: US   Not  geoip: US-

### ISSUE THREAD

**Issue by bmullan** [mycoria/mycoria#3]
$./mycoria config generate
Got country code from geoip: **US-**

**Error: country code from geoip is invalid ("US-"), please set as argument**
Usage:
  mycoria config generate [flags]

Flags:
  -h, --help   help for generate

Global Flags:
      --config string   set config file
      --devmode         enable development mode
      --log string      set log level

**Comment by bmullan** [comment]
Also,   The help displayed above  says FLAG for help   --help

But I can find now way to display what **"Flags"** are available.

That should probably be added to:

> **$ mycoria -h**

**Comment by bmullan** [comment]
well despite no "help" info on the command syntax to fix the above error I must of tried 50 different syntax guesses and
finally got it to work ??

so this worked for me:

**$ ./mycoria config generate US-NC**

**Comment by dhaavi** [comment]
Thanks for the feedback and hanging in there!

Improved in [v0.5.1](https://github.com/mycoria/mycoria/releases/tag/v0.5.1)!
