### ISSUE TITLE
How to configure Mycoria to route local host subnets through the VPN

### ISSUE THREAD

**Issue by bmullan** [mycoria/mycoria#4]
I use Ubuntu 

LXD is a "system" Container and VM management tool
By "system" Container its meant that  LXD containers run a complete Distro but share the Kernel of the Host server.

Incus was a recent Fork of LXD.

Example using Incus
**$ incus launch images:ubuntu:24.04 test1**
would create a new container called test1 which is more or less the same as an Ubuntu 24.04 server.   
You can install anything in that Container you want, including a Desktop if desired.

**$ incus exec test bash** 
_root@test # apt update && apt upgrade -y &&   apt install nano -y_

For both LXD and Incus, their containers run behind a NAT'd Bridge Interface (for LXD its lxdbr0, for Incus its incusbr0).
The lxdbr0/incusbr0 bridge's have a default 10.x.x.x/24 address (they also have an IPv6) 

All Containers created behind that bridge also get a 10.x.x.x. address & an IPv6

An excerpt of "**ip a**" on one of my system's with both Incus and Mycoria installed

> 4: **mycoria:** <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast state UNKNOWN group default qlen 500
>     link/none 
>     **inet6 fd43:8ad2:7b1a:e6a6:9c0b:a423:dd1e:f4ff/8 scope global** 
>        valid_lft forever preferred_lft forever
>     **inet6 fe80::c530:915d:16f2:2552/64 scope link stable-privacy** 
>        valid_lft forever preferred_lft forever
> 5: **lxdbr0:** <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
>     link/ether 00:16:3e:32:c6:7f brd ff:ff:ff:ff:ff:ff
>     i**net 10.48.72.1/24** scope global lxdbr0
>        valid_lft forever preferred_lft forever
>     **inet6 fd42:747:69d1:8696::1/64 scope global** 
>        valid_lft forever preferred_lft forever
>     **inet6 fe80::216:3eff:fe32:c67f/64 scope link** 
>        valid_lft forever preferred_lft forever

### My Question is...

**_Can Mycoria route local Host Subnet traffic like the 10.x.x.x of these Containers through its Tunnels._**

**_With Wireguard this is done using "**allowed-ips**" in the wg0.conf file such as:_**

> [Interface]
> Address = 192.168.7.1,fd42:42:42::1/64
> PrivateKey = contents_of_file_privatekey
> ListenPort = 51820
> 
> #client1
> [Peer]
> PublicKey = contents_of_publickey_of_client
> **AllowedIPs = 10.48.72.1/24,aaaa:bbbb:cccc:dddd:ffff::2/128**

In my past work with implementing wireguard mesh vpn and lxd/incus containers I only had to 
install Wireguard in the Host Server and **set the Wireguard config** with:

_So for the example **lxdbr0 interface** shown in the ip a above setting:_
**AllowedIPs = 10.48.72.1**

Since ALL the other containers are behind that lxdbr0 interface (10.48.72.1) 
THEN.... 
traffic from ALL those containers becomes included in the Wireguard Tunnel

**_This gives the benefit_** of a Container on AWS being able to talk directly to a Container on Digital Ocean
despite those both those Containers being a non-routable IP subnet.

_Can this be done with Mycoria or Mycoria's Config file somehow?_   

**_Is the above description what your Mycoria Configure page talks about "Friends" and shows as:_**

> \# You can also allow services only for friends or a custom list of routers.
> - name: Secret Portal
>   url: 'tcp://:81'
>   \# Allow all friends.
>   **friends: true**
>   **\# Allow a list of router IPs or friend names.**
>   for:
>   ***- fd1f:14ed:bc18:ecb1:af00:9a2d:2a76:201d***
>   - alice
> 
> \# Choose your friends wisely.
> \# Friends are used for simplified access control.
> \# You can only allow connections to friends with "isolate=true"
> \# You can only allow connections from friends to a service with "friends=true"
> \# If you have setup your DNS for Mycoria, you can also resolve their names.
> **friends:**
> - name: alice \# Resolves as alice.myco.
>   ip: fd1f:2cd5:6feb:7aa7:d674:1b3c:c82c:dfc
> - name: bob \# Resolves as bob.myco.
>   ip: fd11:6e6d:b98a:538d:67e5:5244:8e98:9f6e
> 

thanks for any insight.
brian

**Comment by dhaavi** [comment]
Mycoria does not yet support routing another subnet through it.
We are still collecting requirements and limitations:
- Eg. IPv4 address conflicts, internal translation and referencing, NATing on destination, and so on.

What you can do now is, to stick with IPv6 and use SNAT on source and port forwarding on the destination. (There is NAT46, but support seems to be bad.)

So:
- Assign any fc00::/8 address to the container. (Mycoria uses fd00::/8)
- SNAT on the mycoria interface.
- On destination, DNAT or port forward to your service.
- Access the service using the Mycoria address of the destination.

If you can tell us in detail what your requirements are, we can let them flow into the design process.

**Comment by bmullan** [comment]
Thanks... for the information.
_Getting that subnet routing capability_ will be important to Docker, LXD and Incus Container users.

**Comment by bmullan** [comment]
@dhaavi 

You asked:     
> **If you can tell us in detail what your requirements are, we can let them flow into the design process.**

I made 2 different diagrams _which I hope are self-explanatory enough to understand the intent._    
1. **_Single-Tenant, Multi-Cloud_** LXD or Incus System Container based Architecture
2. **_Multi-Tenant, Multi-Cloud_** LXD or Incus System Container based Architecture

NOTE:  

I have done these 2 same Architectures several years ago but used Wireguard, FRR for BGP (for L3) & VxLAN (for L2).
In the **_Multi-Tenant Model_,  VxLAN was configured in each Host**.

**_On each Host_** the LXD or Incus Container (or VM) Bridges (lxdbr0-lxdbrN or incusbr0-incusbrN) were assigned a different VNI to isolate each **_Tenant's_** 

_Referencing the Multi-Tenant diagram:_   

On Host 1, Host 2, Host 3 ... lxdbrX or incusbrX bridges where assigned the VNI of their respective Tenant.  
- Tenant A might be VNI 100
- Tenant B might be VNI 200
- Tenant C might be VNI 300

As you probably know VxLAN does not do encryption... that's what the Wireguard was for.
So the VxLAN traffic one each Cloud Host Node was tunneled through Wireguard to other Host Nodes.

BGP's routing allowed _automatic discovery/routing_ of any Tenant Containers/VMs,  added to -or- deleted from, any of the Host Node Servers.

There was a big benefit of that approach  because ti eliminated the usual problems of Internet Broadcast, unknown Unicast and Multicast (BUM) traffic over the Internet.

Anyway... here is a link to my Install Guide on Github:   ***[CIAB Full Mesh VPN Internet Overlay](https://github.com/bmullan/

Attached are  the Single & Multi-Tenant diagrams I made to try & illustrate what this did:

[Mesh VPN for Containers Multi-Tenant Model.pdf](https://github.com/user-attachments/files/16056189/Mesh.VPN.for.Containers.Multi-Tenant.Model.pdf)
[Mesh VPN for Containers - Single-Tenant Model.pdf](https://github.com/user-attachments/files/16056190/Mesh.VPN.for.Containers.-.Single-Tenant.Model.pdf)

CIAB.Full-Mesh.VPN.Wireguard.FRR.BGP.VXLAN.Internet.Overlay.Architecture)***

**Comment by bmullan** [comment]
@dhaavi 

I'd told a friend of mine named Craig about what I know of Mycoria so far.
Craig is an expert with IPv6 having been a lead network consultant for Microsoft & a large telecom in his career.
He's been working with IPv6 since 2012 on ARIN's IPv6 launch day.

Anyway Craig hasn't had time to look deeply into Mycoria yet but with his cursory look he said:

> - The use of ULAs to create a hashed address. While this may work for router IDs, I would think just hashing the last 64  
>    bits (aka the IID or Interface ID) would accomplish the same, and would allow them to use Global Unique Addresses  
>  
> - The Overlay Network. This means that no matter how smart your L2 switch is at popping L2 headers     
>    (_which is kind of like MPLS_), performance is still limited by the underlying infrastructure.

The above is just to share some info.

brian

**Comment by dhaavi** [comment]
Hey @bmullan, thanks for all the input!

I have started working on the concept for routing foreign networks over Mycoria.

Just wanted to check something with you: What I think would become too complex to handle in a stable and easy way is to have the same foreign subnet on both sides, as Mycoria would need to figure which IPs would be on which side.

So, having three servers and all of them having their own network (eg. 10.0.1.0/24 and 10.0.2.0/24 and so on) would work perfectly.

(In some cases, however, the source IPs would not be meaningful and would probably just be random addresses from the internal ISP range (100.64/10) - this is required to guarantee the return packets take the correct path back. But normally if all packets come from defined ranges, this should work out without needing to change addresses.)
